#include <jimmy.h>
char *jimmy = "\n"
"                -WWSSHWMWWWW(--        \n"
"              W--- = ==  -  ====M<     \n"
"            >M=------      ---  =WLK   \n"
"            M--- --                L   \n"
"            M     ___ ___        --M-  \n"
"             =    =      _     __  K<  \n"
"            >P  ______  ( )          L \n"
"            - P[_o_o_]     ---       M-\n"
"            M  /     |   ^= ^=       WL\n"
"            =- |    /   = == ^=     L< \n"
"             M \\   |               W<- \n"
"             -M=\\_/          --     WW-\n"
"               K--------------------L  \n";
